buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Actualiza esta línea a la versión 8.2.1 del plugin de Android Gradle
        classpath 'com.android.tools.build:gradle:8.2.1'  // Asegúrate de tener esta versión
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
